### ISSUE TITLE
Netlify CMS not showing pages

### ISSUE THREAD

**Issue by tyler71** [ledstrain/wiki.ledstrain.org#11]
https://wiki.ledstrain.org/contribute

```
backend:                                                                        
  name: github                                                                  
  repo: ledstrain/wiki.ledstrain.org                                            
  open_authoring: true                                                          
                                                                                
publish_mode: editorial_workflow                                                
                                                                                
media_folder: "static/assets/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
                                                                                
collections: # A list of collections the CMS should be able to edit             
  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit          
    label: "Pages" # Used in the UI, ie.: "New Post"                            
    folder: "content/docs" # The path to the folder where the documents are stored
    extension: "md"                                                             
    create: false # Allow users to create new documents in this collection      
    fields: # The fields each document in this collection have                  
      - {label: "Title", name: "title", widget: "string"}                       
      - {label: "Weight", name: "weight", widget: "hidden"}                     
      - {label: "bookToc", name: "booktoc", widget: "hidden"}                   
      - {label: "Body", name: "body", widget: "markdown"}
```

![image](https://user-images.githubusercontent.com/4926565/72087422-45d4c080-32bd-11ea-81f1-f2b591c6840c.png)

It showed pages when I changed the folder to content/posts and put some *.md files in there.
Next steps would probably be removing one directory at a time until pages show up to see if there's a badly formatted directory.
